### ISSUE TITLE
[Bug] In the readme, the support server embed doesn't exist anymore

### ISSUE THREAD

**Issue by recallwhoiam** [FreeTechnologies/FreeDiscord#9]
NOTE: Always try updating the bot BEFORE making an issue

**Describe the bug**
In the readme, the support server embed doesn't exist anymore

**To Reproduce**
Just go to the readme lol

**Error**
N/A

**Screenshots**
N/A

**Desktop**
- Arch Linux

**Additional context**
N/A

**Comment by ItsJustLag** [comment]
not sure how to fix this, https://discordapp.com/api/guilds/827948403698696193/widget.png?style=banner3 doesnt really exist, it errors. you'll have to remake the link and edit the readme since idk how to do it

**Comment by recallwhoiam** [comment]
> not sure how to fix this, https://discordapp.com/api/guilds/827948403698696193/widget.png?style=banner3 doesnt really exist, it errors. you'll have to remake the link and edit the readme since idk how to do it

Yeah its for the old server

**Comment by recallwhoiam** [comment]
ill fix it later

**Comment by recallwhoiam** [comment]
fixed
